### PR TITLE
fix: missing cwd for CLI arguments that rely on it [ROAD-635]

### LINKED ISSUE #128: Scan Failed
When attempting to test a .NET solution with --file=.sln I run into "Scan failed" with the attached error. Note that I am authenticated and can successfully run `snyk test --file=.sln` from the command line.

image

### PR DESCRIPTION
**Pull request by michelkaporin**
Fixes #128

### CODE REVIEW

File: src/snyk/cli/services/cliService.ts [hunk 1]
```diff
@@ -64,12 +64,17 @@ export abstract class CliService<CliResult> extends AnalysisStatusProvider {
...
+    }
+
     this.cliProcess = new CliProcess(this.logger, this.config);
-    const args = this.buildArguments();
+    const args = this.buildArguments(foldersToTest);
 
     let output: string;
     try {
-      output = await this.cliProcess.spawn(cliPath, args);
+      output = await this.cliProcess.spawn(cliPath, foldersToTest[0], args);
```
Comment (bastiandoetsch) [inline src/snyk/cli/services/cliService.ts:77]: Why limit this to one folder and not loop over all?

Comment (michelkaporin) [reply src/snyk/cli/services/cliService.ts:77]: Would you spawn multiple CLI processes with different cwds?

Comment (bastiandoetsch) [reply src/snyk/cli/services/cliService.ts:77]: yes!

Comment (michelkaporin) [reply src/snyk/cli/services/cliService.ts:77]: That would be an option but would require some rework around how we handle reports from multiple CLI instances. Since there's no actual need for that at the moment, I would not be addressing it in this PR.

**Review by bastiandoetsch — APPROVED** [review]
